export const MESES = {
  ENERO: 'ENERO',
  FEBRERO: 'FEBRERO',
  MARZO: 'MARZO',
  ABRIL: 'ABRIL',
  MAYO: 'MAYO',
  JUNIO: 'JUNIO',
  JULIO: 'JULIO',
  AGOSTO: 'AGOSTO',
  SEPTIEMBRE: 'SEPTIEMBRE',
  OCTUBRE: 'OCTUBRE',
  NOVIEMBRE: 'NOVIEMBRE',
  DICIEMBRE: 'DICIEMBRE',
} as const

export type Mes = (typeof MESES)[keyof typeof MESES]
